import { Injectable } from '@angular/core';

import { Moeda } from './moeda.model';

@Injectable({
  providedIn: 'root'
})
export class MoedaService {

  private moedas: Moeda[];

  constructor() { }

  private moedasObj = [
    { "sigla": "AED", "descricao": "United Arab Emirates Dirham" },
    { "sigla": "AFN", "descricao": "Afghan Afghani" },
    { "sigla": "ALL", "descricao": "Albanian Lek" },
    { "sigla": "AMD", "descricao": "Armenian Dram" },
    { "sigla": "ANG", "descricao": "Netherlands Antillean Guilder" },
    { "sigla": "AOA", "descricao": "Angolan Kwanza" },
    { "sigla": "ARS", "descricao": "Argentine Peso" },
    { "sigla": "AUD", "descricao": "Australian Dollar" },
    { "sigla": "AWG", "descricao": "Aruban Florin" },
    { "sigla": "AZN", "descricao": "Azerbaijani Manat" },
    { "sigla": "BAM", "descricao": "Bosnia - Herzegovina Convertible Mark" },
    { "sigla": "BBD", "descricao": "Barbadian Dollar" },
    { "sigla": "BDT", "descricao": "Bangladeshi Taka" },
    { "sigla": "BGN", "descricao": "Bulgarian Lev" },
    { "sigla": "BHD", "descricao": "Bahraini Dinar" },
    { "sigla": "BIF", "descricao": "Burundian Franc" },
    { "sigla": "BMD", "descricao": "Bermudan Dollar" },
    { "sigla": "BND", "descricao": "Brunei Dollar" },
    { "sigla": "BOB", "descricao": "Bolivian Boliviano" },
    { "sigla": "BRL", "descricao": "Brazilian Real" },
    { "sigla": "BSD", "descricao": "Bahamian Dollar" },
    { "sigla": "BTC", "descricao": "Bitcoin" },
    { "sigla": "BTN", "descricao": "Bhutanese Ngultrum" },
    { "sigla": "BWP", "descricao": "Botswanan Pula" },
    { "sigla": "BYR", "descricao": "Belarusian Ruble" },
    { "sigla": "BZD", "descricao": "Belize Dollar" },
    { "sigla": "CAD", "descricao": "Canadian Dollar" },
    { "sigla": "CDF", "descricao": "Congolese Franc" },
    { "sigla": "CHF", "descricao": "Swiss Franc" },
    { "sigla": "CLF", "descricao": "Chilean Unit of Account(UF)" },
    { "sigla": "CLP", "descricao": "Chilean Peso" },
    { "sigla": "CNY", "descricao": "Chinese Yuan" },
    { "sigla": "COP", "descricao": "Colombian Peso" },
    { "sigla": "CRC", "descricao": "Costa Rican Colón" },
    { "sigla": "CUC", "descricao": "Cuban Convertible Peso" },
    { "sigla": "CUP", "descricao": "Cuban Peso" },
    { "sigla": "CVE", "descricao": "Cape Verdean Escudo" },
    { "sigla": "CZK", "descricao": "Czech Republic Koruna" },
    { "sigla": "DJF", "descricao": "Djiboutian Franc" },
    { "sigla": "DKK", "descricao": "Danish Krone" },
    { "sigla": "DOP", "descricao": "Dominican Peso" },
    { "sigla": "DZD", "descricao": "Algerian Dinar" },
    { "sigla": "EGP", "descricao": "Egyptian Pound" },
    { "sigla": "ERN", "descricao": "Eritrean Nakfa" },
    { "sigla": "ETB", "descricao": "Ethiopian Birr" },
    { "sigla": "EUR", "descricao": "Euro" },
    { "sigla": "FJD", "descricao": "Fijian Dollar" },
    { "sigla": "FKP", "descricao": "Falkland Islands Pound" },
    { "sigla": "GBP", "descricao": "British Pound Sterling" },
    { "sigla": "GEL", "descricao": "Georgian Lari" },
    { "sigla": "GGP", "descricao": "Guernsey Pound" },
    { "sigla": "GHS", "descricao": "Ghanaian Cedi" },
    { "sigla": "GIP", "descricao": "Gibraltar Pound" },
    { "sigla": "GMD", "descricao": "Gambian Dalasi" },
    { "sigla": "GNF", "descricao": "Guinean Franc" },
    { "sigla": "GTQ", "descricao": "Guatemalan Quetzal" },
    { "sigla": "GYD", "descricao": "Guyanaese Dollar" },
    { "sigla": "HKD", "descricao": "Hong Kong Dollar" },
    { "sigla": "HNL", "descricao": "Honduran Lempira" },
    { "sigla": "HRK", "descricao": "Croatian Kuna" },
    { "sigla": "HTG", "descricao": "Haitian Gourde" },
    { "sigla": "HUF", "descricao": "Hungarian Forint" },
    { "sigla": "IDR", "descricao": "Indonesian Rupiah" },
    { "sigla": "ILS", "descricao": "Israeli New Sheqel" },
    { "sigla": "IMP", "descricao": "Manx pound" },
    { "sigla": "INR", "descricao": "Indian Rupee" },
    { "sigla": "IQD", "descricao": "Iraqi Dinar" },
    { "sigla": "IRR", "descricao": "Iranian Rial" },
    { "sigla": "ISK", "descricao": "Icelandic Króna" },
    { "sigla": "JEP", "descricao": "Jersey Pound" },
    { "sigla": "JMD", "descricao": "Jamaican Dollar" },
    { "sigla": "JOD", "descricao": "Jordanian Dinar" },
    { "sigla": "JPY", "descricao": "Japanese Yen" },
    { "sigla": "KES", "descricao": "Kenyan Shilling" },
    { "sigla": "KGS", "descricao": "Kyrgystani Som" },
    { "sigla": "KHR", "descricao": "Cambodian Riel" },
    { "sigla": "KMF", "descricao": "Comorian Franc" },
    { "sigla": "KPW", "descricao": "North Korean Won" },
    { "sigla": "KRW", "descricao": "South Korean Won" },
    { "sigla": "KWD", "descricao": "Kuwaiti Dinar" },
    { "sigla": "KYD", "descricao": "Cayman Islands Dollar" },
    { "sigla": "KZT", "descricao": "Kazakhstani Tenge" },
    { "sigla": "LAK", "descricao": "Laotian Kip" },
    { "sigla": "LBP", "descricao": "Lebanese Pound" },
    { "sigla": "LKR", "descricao": "Sri Lankan Rupee" },
    { "sigla": "LRD", "descricao": "Liberian Dollar" },
    { "sigla": "LSL", "descricao": "Lesotho Loti" },
    { "sigla": "LTL", "descricao": "Lithuanian Litas" },
    { "sigla": "LVL", "descricao": "Latvian Lats" },
    { "sigla": "LYD", "descricao": "Libyan Dinar" },
    { "sigla": "MAD", "descricao": "Moroccan Dirham" },
    { "sigla": "MDL", "descricao": "Moldovan Leu" },
    { "sigla": "MGA", "descricao": "Malagasy Ariary" },
    { "sigla": "MKD", "descricao": "Macedonian Denar" },
    { "sigla": "MMK", "descricao": "Myanma Kyat" },
    { "sigla": "MNT", "descricao": "Mongolian Tugrik" },
    { "sigla": "MOP", "descricao": "Macanese Pataca" },
    { "sigla": "MRO", "descricao": "Mauritanian Ouguiya" },
    { "sigla": "MUR", "descricao": "Mauritian Rupee" },
    { "sigla": "MVR", "descricao": "Maldivian Rufiyaa" },
    { "sigla": "MWK", "descricao": "Malawian Kwacha" },
    { "sigla": "MXN", "descricao": "Mexican Peso" },
    { "sigla": "MYR", "descricao": "Malaysian Ringgit" },
    { "sigla": "MZN", "descricao": "Mozambican Metical" },
    { "sigla": "NAD", "descricao": "Namibian Dollar" },
    { "sigla": "NGN", "descricao": "Nigerian Naira" },
    { "sigla": "NIO", "descricao": "Nicaraguan Córdoba" },
    { "sigla": "NOK", "descricao": "Norwegian Krone" },
    { "sigla": "NPR", "descricao": "Nepalese Rupee" },
    { "sigla": "NZD", "descricao": "New Zealand Dollar" },
    { "sigla": "OMR", "descricao": "Omani Rial" },
    { "sigla": "PAB", "descricao": "Panamanian Balboa" },
    { "sigla": "PEN", "descricao": "Peruvian Nuevo Sol" },
    { "sigla": "PGK", "descricao": "Papua New Guinean Kina" },
    { "sigla": "PHP", "descricao": "Philippine Peso" },
    { "sigla": "PKR", "descricao": "Pakistani Rupee" },
    { "sigla": "PLN", "descricao": "Polish Zloty" },
    { "sigla": "PYG", "descricao": "Paraguayan Guarani" },
    { "sigla": "QAR", "descricao": "Qatari Rial" },
    { "sigla": "RON", "descricao": "Romanian Leu" },
    { "sigla": "RSD", "descricao": "Serbian Dinar" },
    { "sigla": "RUB", "descricao": "Russian Ruble" },
    { "sigla": "RWF", "descricao": "Rwandan Franc" },
    { "sigla": "SAR", "descricao": "Saudi Riyal" },
    { "sigla": "SBD", "descricao": "Solomon Islands Dollar" },
    { "sigla": "SCR", "descricao": "Seychellois Rupee" },
    { "sigla": "SDG", "descricao": "Sudanese Pound" },
    { "sigla": "SEK", "descricao": "Swedish Krona" },
    { "sigla": "SGD", "descricao": "Singapore Dollar" },
    { "sigla": "SHP", "descricao": "Saint Helena Pound" },
    { "sigla": "SLL", "descricao": "Sierra Leonean Leone" },
    { "sigla": "SOS", "descricao": "Somali Shilling" },
    { "sigla": "SRD", "descricao": "Surinamese Dollar" },
    { "sigla": "STD", "descricao": "São Tomé and Príncipe Dobra" },
    { "sigla": "SVC", "descricao": "Salvadoran Colón" },
    { "sigla": "SYP", "descricao": "Syrian Pound" },
    { "sigla": "SZL", "descricao": "Swazi Lilangeni" },
    { "sigla": "THB", "descricao": "Thai Baht" },
    { "sigla": "TJS", "descricao": "Tajikistani Somoni" },
    { "sigla": "TMT", "descricao": "Turkmenistani Manat" },
    { "sigla": "TND", "descricao": "Tunisian Dinar" },
    { "sigla": "TOP", "descricao": "Tongan Paʻanga" },
    { "sigla": "TRY", "descricao": "Turkish Lira" },
    { "sigla": "TTD", "descricao": "Trinidad and Tobago Dollar" },
    { "sigla": "TWD", "descricao": "New Taiwan Dollar" },
    { "sigla": "TZS", "descricao": "Tanzanian Shilling" },
    { "sigla": "UAH", "descricao": "Ukrainian Hryvnia" },
    { "sigla": "UGX", "descricao": "Ugandan Shilling" },
    { "sigla": "USD", "descricao": "United States Dollar" },
    { "sigla": "UYU", "descricao": "Uruguayan Peso" },
    { "sigla": "UZS", "descricao": "Uzbekistan Som" },
    { "sigla": "VEF", "descricao": "Venezuelan Bolívar Fuerte" },
    { "sigla": "VND", "descricao": "Vietnamese Dong" },
    { "sigla": "VUV", "descricao": "Vanuatu Vatu" },
    { "sigla": "WST", "descricao": "Samoan Tala" },
    { "sigla": "XAF", "descricao": "CFA Franc BEAC" },
    { "sigla": "XAG", "descricao": "Silver(troy ounce)" },
    { "sigla": "XAU", "descricao": "Gold(troy ounce)" },
    { "sigla": "XCD", "descricao": "East Caribbean Dollar" },
    { "sigla": "XDR", "descricao": "Special Drawing Rights" },
    { "sigla": "XOF", "descricao": "CFA Franc BCEAO" },
    { "sigla": "XPF", "descricao": "CFP Franc" },
    { "sigla": "YER", "descricao": "Yemeni Rial" },
    { "sigla": "ZAR", "descricao": "South African Rand" },
    { "sigla": "ZMK", "descricao": "Zambian Kwacha(pre - 2013)" },
    { "sigla": "ZMW", "descricao": "Zambian Kwacha" },
    { "sigla": "ZWL", "descricao": "Zimbabwean Dollar" },
  ];


  listarTodas(): Moeda[] {
    if (this.moedas) { return this.moedas; }

    this.moedas = [];

    for (let moedaObj of this.moedasObj) {
      let moeda: Moeda = new Moeda();
      Object.assign(moeda, moedaObj);
      this.moedas.push(moeda);
    }

    return this.moedas;
  }

}
